name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List Files
        run: ls -la

      # Install SonarScanner CLI
      - name: Install SonarScanner
        run: npm install -g sonar-scanner

      # Make script executable
      - name: Grant Execute Permission
        run: chmod +x run-quality.sh

      # Run your wrapper
      - name: Run Quality Script
        run: ./run-quality.sh

  
